module.exports =  {
  es6:"/images/post/es6.jpeg",
  JavaScript:"/images/post/JavaScript.jpeg",
  TypeScript:"/images/post/TypeScript.jpeg",
  css:"/images/post/css.jpeg",
  node:"/images/post/nodejs.jpeg",
  vue:"/images/post/vue.jpeg",
  webpack:"/images/post/webpack.jpeg",
  git:"/images/post/git.jpeg",
  java:"/images/post/java.jpg",
  echarts:"/images/post/echarts.jpg",
  微信小程序:"/images/post/wechat_applet.jpg",
  浏览器:"/images/post/browser.jpeg",
  算法:"/images/post/algorithm.jpeg",
  数据结构:"/images/post/data.jpg",
  工具:"/images/post/editor.jpeg",
  UI库:"/images/post/ui.jpg",
  美化:"/images/post/beautify.jpg"
}
