module.exports =  {
  es6:"/images/post/es6.png",
  JavaScript:"/images/post/JavaScript.png",
  TypeScript:"/images/post/TypeScript.png",
  css:"/images/post/css.png",
  node:"/images/post/nodejs.png",
  react:"/images/post/react.png",
  webpack:"/images/post/webpack.png",
  git:"/images/post/git.png",
  java:"/images/post/java.png",
  echarts:"/images/post/echarts.png",
  微信小程序:"/images/post/wechat_applet.png",
  浏览器:"/images/post/browser.png",
  算法:"/images/post/algorithm.png",
  数据结构:"/images/post/data.png",
  工具:"/images/post/editor.png",
  UI库:"/images/post/ui.png",
  美化:"/images/post/beautify.png"
}
